### ISSUE TITLE
Error: expression 'tkPseudoEmpty' is of type 'TokenKind' and has to be discarded

### ISSUE THREAD

**Issue by shinriyo** [GULPF/nimquery#2]
Hello.
I just tried to code in README.

I paste your code in `script.nim`.
`nim c -r script.nim`

the error occurred.
```
/Users/shinriyo/.nimble/pkgs/nimquery-1.1.0/nimquery.nim(632, 29) Error: expression 'tkPseudoEmpty' is of type 'TokenKind' and has to be discarded
```

```
$ nim --version
Nim Compiler Version 0.17.2 (2017-09-18) [MacOSX: amd64]
```

**Comment by GULPF** [comment]
Hello!

Nimquery only works with the latest stable release of Nim (version 0.18.0). I'll update the nimble file to indicate this, so that Nimble will complain when the Nim version is to old.
