### ISSUE TITLE
Modify HTML DOM?

### ISSUE THREAD

**Issue by ankush981** [GULPF/nimquery#7]
Hello, just wanted to know if it's possible to modify HTML DOM using this library? If not, are there any options in the Nim ecosystem currently? Thanks! :smile:

**Comment by GULPF** [comment]
There's no special support for mutations in nimquery, but the [xmltree](https://nim-lang.org/docs/xmltree.html) module from the standard library (which nimquery uses) supports it. It's not a very ergonomic way to work with HTML, but it's the only thing available in Nim afaik. Example:

```nim
import xmltree
from htmlparser import parseHtml
import nimquery

let html = """
<!DOCTYPE html>
<html>
  <head><title>Example</title></head>
  <body>
    <p>1</p>
    <p>2</p>
    <p>3</p>
    <p>4</p>
  </body>
</html>
"""
let xml = parseHtml(newStringStream(html))
let elements = xml.querySelector("p")
elements[0].text = "replaced"
echo $xml
# Output:
# <document>
# <html>
#   <head><title>Example</title></head>
#   <body>
#     <p>replaced</p>
#     <p>2</p>
#     <p>3</p>
#     <p>4</p>
#   </body>
# </html>
# </document>

```

**Comment by ankush981** [comment]
Thank you!
